preprocess:
  input: data/raw/diabetes.csv
  output: data/preprocessed/data.csv

train:
  data: data/preprocessed/data.csv
  model_path: models.pkl
  random_state: 42
  n_estimators: 100
  max_depth: 10
  

dagshub:
  MLFLOW_TRACKING_URI: https://dagshub.com/Em0ani/testrepo.mlflow